### PR TITLE
Abstract Data Class

### PR DESCRIPTION
**Pull request by crangelsmith**
Part of #3 

- File with abstract Dataset class
- This is a rebase, it should be merged after #8.

PR just because we said we will merge to main once a day. I will work on the rest of #3 next.

### CODE REVIEW

**Comment by JamesJordon** [comment]
It would be good to add an abstract method for sub-sampling the data (`split` could arguably then be concretely implemented in a basic way given a sub-sampling method), and maybe even for sampling a single "row" (though obviously row doesn't have a consistent meaning across dataset types). All dataset types will also need to support dropping a row/set of rows and adding a row in, whatever that might mean. So I guess I'm suggesting the following abstract methods: `sample`, `sample_row`, `drop`, `add` (maybe `add` could be called `include`). Maybe also a `replace` method to allow investigation of bounded privacy notions (e.g. bounded differential privacy).

**Comment by crangelsmith** [comment]
> It would be good to add an abstract method for sub-sampling the data (`split` could arguably then be concretely implemented in a basic way given a sub-sampling method), and maybe even for sampling a single "row" (though obviously row doesn't have a consistent meaning across dataset types). All dataset types will also need to support dropping a row/set of rows and adding a row in, whatever that might mean. So I guess I'm suggesting the following abstract methods: `sample`, `sample_row`, `drop`, `add` (maybe `add` could be called `include`). Maybe also a `replace` method to allow investigation of bounded privacy notions (e.g. bounded differential privacy).

Sounds good! I think in my mind the `split` method was equivalent to what you describe as `sample`, which makes more sense as a name for the method btw. For you, the split method is equivalent to the scikit learn method? 

I'm not sure what the replace method is meant to do specifically, can you give more details?

**Comment by JamesJordon** [comment]
'replace' would basically be shorthand for calling 'sample(1)', 'drop' on the result of 'sample', and then 'add'. So replace a random row with a given row. This could probably be a concrete implementation in the base class, rather than abstract.

**Comment by crangelsmith** [comment]
Update:

- I've added a minimal implementation of the TabularDataset Class, the read function, more to come!
- But more importantly, we have a first test based on the texas data and an associated CI! 

There is a lot more to implement on the Tabular dataset but i wanted to have a testing setup ready asap.

**Pull request merged**
